provider:
  name: aws
  stage: test
  region: eu-central-1
  runtime: nodejs8.10

plugins:
  - serverless-domain-manager
  - serverless-haskell
  - serverless-offline

service:
  name: "morpheus-graphql-mythology-api-${self:provider.stage}"
  domain: "api.morpheusgraphql.com"

package:
  excludeDevDependencies: false
  exclude:
    - app/**
    - src/**
    - .stack-work/**
    - node_modules/**

custom:
  serverless-offline:
    resourceRoutes: true
    port: 3000
  customDomain:
    domainName: "${self:service.domain}"
    stage: ${self:provider.stage}
    createRoute53Record: true

functions:
  graphql:
    handler: mythology-api.graphql
    events:
      - http: POST /
      - http: GET /
